// <auto-generated />
using System;
using Analytics.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Analytics.API.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20251222094604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Analytics.API.Data.Entities.AnalyticsEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Browser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("browser");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("Device")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("device");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_name");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("OS")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("os");

                    b.Property<string>("PageTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("page_title");

                    b.Property<string>("Referrer")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("referrer");

                    b.Property<int?>("ScreenHeight")
                        .HasColumnType("integer")
                        .HasColumnName("screen_height");

                    b.Property<int?>("ScreenWidth")
                        .HasColumnType("integer")
                        .HasColumnName("screen_width");

                    b.Property<int?>("SessionDuration")
                        .HasColumnType("integer")
                        .HasColumnName("session_duration");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.Property<string>("UrlPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url_path");

                    b.Property<string>("VisitorId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id");

                    b.HasIndex("EventName")
                        .HasDatabaseName("ix_events_event_name");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_events_timestamp");

                    b.HasIndex("VisitorId")
                        .HasDatabaseName("ix_events_visitor_id");

                    b.HasIndex("TenantId", "Timestamp")
                        .HasDatabaseName("ix_events_tenant_timestamp");

                    b.ToTable("analytics_events");
                });

            modelBuilder.Entity("Analytics.API.Data.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("api_key");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("domain");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_api_key");

                    b.HasIndex("Domain")
                        .HasDatabaseName("ix_tenants_domain");

                    b.ToTable("tenants");
                });
#pragma warning restore 612, 618
        }
    }
}
