// Country code to flag emoji and name mapping
export const countryData: Record<string, { flag: string; name: string }> = {
  TR: { flag: "🇹🇷", name: "Türkiye" },
  US: { flag: "🇺🇸", name: "United States" },
  DE: { flag: "🇩🇪", name: "Germany" },
  GB: { flag: "🇬🇧", name: "United Kingdom" },
  FR: { flag: "🇫🇷", name: "France" },
  JP: { flag: "🇯🇵", name: "Japan" },
  BR: { flag: "🇧🇷", name: "Brazil" },
  IN: { flag: "🇮🇳", name: "India" },
  AU: { flag: "🇦🇺", name: "Australia" },
  CA: { flag: "🇨🇦", name: "Canada" },
  NL: { flag: "🇳🇱", name: "Netherlands" },
  ES: { flag: "🇪🇸", name: "Spain" },
  IT: { flag: "🇮🇹", name: "Italy" },
  RU: { flag: "🇷🇺", name: "Russia" },
  CN: { flag: "🇨🇳", name: "China" },
  KR: { flag: "🇰🇷", name: "South Korea" },
  MX: { flag: "🇲🇽", name: "Mexico" },
  AR: { flag: "🇦🇷", name: "Argentina" },
  SE: { flag: "🇸🇪", name: "Sweden" },
  NO: { flag: "🇳🇴", name: "Norway" },
  DK: { flag: "🇩🇰", name: "Denmark" },
  FI: { flag: "🇫🇮", name: "Finland" },
  PL: { flag: "🇵🇱", name: "Poland" },
  PT: { flag: "🇵🇹", name: "Portugal" },
  CH: { flag: "🇨🇭", name: "Switzerland" },
  AT: { flag: "🇦🇹", name: "Austria" },
  BE: { flag: "🇧🇪", name: "Belgium" },
  IE: { flag: "🇮🇪", name: "Ireland" },
  NZ: { flag: "🇳🇿", name: "New Zealand" },
  SG: { flag: "🇸🇬", name: "Singapore" },
  HK: { flag: "🇭🇰", name: "Hong Kong" },
  TW: { flag: "🇹🇼", name: "Taiwan" },
  TH: { flag: "🇹🇭", name: "Thailand" },
  ID: { flag: "🇮🇩", name: "Indonesia" },
  MY: { flag: "🇲🇾", name: "Malaysia" },
  PH: { flag: "🇵🇭", name: "Philippines" },
  VN: { flag: "🇻🇳", name: "Vietnam" },
  ZA: { flag: "🇿🇦", name: "South Africa" },
  EG: { flag: "🇪🇬", name: "Egypt" },
  NG: { flag: "🇳🇬", name: "Nigeria" },
  KE: { flag: "🇰🇪", name: "Kenya" },
  AE: { flag: "🇦🇪", name: "United Arab Emirates" },
  SA: { flag: "🇸🇦", name: "Saudi Arabia" },
  IL: { flag: "🇮🇱", name: "Israel" },
  UA: { flag: "🇺🇦", name: "Ukraine" },
  CZ: { flag: "🇨🇿", name: "Czech Republic" },
  GR: { flag: "🇬🇷", name: "Greece" },
  HU: { flag: "🇭🇺", name: "Hungary" },
  RO: { flag: "🇷🇴", name: "Romania" },
  CL: { flag: "🇨🇱", name: "Chile" },
  CO: { flag: "🇨🇴", name: "Colombia" },
  PE: { flag: "🇵🇪", name: "Peru" },
};

export const getCountryFlag = (countryCode: string): string => {
  return countryData[countryCode]?.flag || "🏳️";
};

export const getCountryName = (countryCode: string): string => {
  return countryData[countryCode]?.name || countryCode;
};

// City to country code mapping for flags
export const cityToCountry: Record<string, string> = {
  "Ankara": "TR",
  "Istanbul": "TR",
  "Izmir": "TR",
  "Frankfurt am Main": "DE",
  "Berlin": "DE",
  "Munich": "DE",
  "Hamburg": "DE",
  "New York": "US",
  "Los Angeles": "US",
  "Chicago": "US",
  "San Francisco": "US",
  "Seattle": "US",
  "Tampa": "US",
  "London": "GB",
  "Manchester": "GB",
  "Paris": "FR",
  "Lyon": "FR",
  "Tokyo": "JP",
  "Osaka": "JP",
  "São Paulo": "BR",
  "Rio de Janeiro": "BR",
  "Mumbai": "IN",
  "Bangalore": "IN",
  "Delhi": "IN",
  "Sydney": "AU",
  "Melbourne": "AU",
  "Toronto": "CA",
  "Vancouver": "CA",
  "Amsterdam": "NL",
  "Madrid": "ES",
  "Barcelona": "ES",
  "Rome": "IT",
  "Milan": "IT",
  "Moscow": "RU",
  "Beijing": "CN",
  "Shanghai": "CN",
  "Seoul": "KR",
  "Singapore": "SG",
  "Hong Kong": "HK",
};

export const getCityCountryCode = (cityName: string): string => {
  return cityToCountry[cityName] || "";
};
